// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCBEJmw58gJ6eHNOO77TfXhas1ugfx898',
    appId: '1:263730048454:web:3283a6c24c6b96919f56c7',
    messagingSenderId: '263730048454',
    projectId: 'mijajoojum',
    authDomain: 'mijajoojum.firebaseapp.com',
    storageBucket: 'mijajoojum.appspot.com',
    measurementId: 'G-Z9TSK84KXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBti_EDkn-2fBdWGGIEq1ZP2PKkXxCohaM',
    appId: '1:263730048454:android:9cffa1ba915647af9f56c7',
    messagingSenderId: '263730048454',
    projectId: 'mijajoojum',
    storageBucket: 'mijajoojum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDza1QX-A1netvmuFFHF3q9uNWLfwozxG4',
    appId: '1:263730048454:ios:6de83ec31116c5cd9f56c7',
    messagingSenderId: '263730048454',
    projectId: 'mijajoojum',
    storageBucket: 'mijajoojum.appspot.com',
    iosBundleId: 'com.example.joojumflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDza1QX-A1netvmuFFHF3q9uNWLfwozxG4',
    appId: '1:263730048454:ios:6de83ec31116c5cd9f56c7',
    messagingSenderId: '263730048454',
    projectId: 'mijajoojum',
    storageBucket: 'mijajoojum.appspot.com',
    iosBundleId: 'com.example.joojumflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCBEJmw58gJ6eHNOO77TfXhas1ugfx898',
    appId: '1:263730048454:web:dbc821c15f4028859f56c7',
    messagingSenderId: '263730048454',
    projectId: 'mijajoojum',
    authDomain: 'mijajoojum.firebaseapp.com',
    storageBucket: 'mijajoojum.appspot.com',
    measurementId: 'G-F9H5SNZJV2',
  );
}
